// Job Actions
// GET REQUESTS
const RETRIEVE_JOBS_LIST = "RETRIEVE_JOBS_LIST";
const RETRIEVE_JOBS_LIST_PAGINATION = "RETRIEVE_JOBS_LIST_PAGINATION";
const RETRIEVE_SINGLE_JOB = "RETRIEVE_SINGLE_JOB";
const RETRIEVE_DATA_ERROR = "RETRIEVE_DATA_ERROR";
const INCREASE_PAGINATION_BEGINNING = "INCREASE_PAGINATION_BEGINNING";
const INCREASE_PAGINATION_ENDING = "INCREASE_PAGINATION_ENDING";
// POST REQUESTS
const ADD_NEW_JOB = "ADD_NEW_JOB";
// PUT REQUESTS
const UPDATE_JOB_INFORMATION = "UPDATE_JOB_INFORMATION";
// DELETE REQUESTS
const DELETE_JOB = "DELETE_JOB";
const INITIALIZE_JOB_STATE = "INITIALIZE_JOB_STATE";
const SUBMITTED_INPUT_COLLECTION = "SUBMITTED_INPUT_COLLECTION";
const UPDATED_INPUT_FIELD = "UPDATED_INPUT_FIELD";

// UI Actions
// APPLICATION FORM TYPES
const VALID_COMPANY_NAME = "VALID_COMPANY_NAME";
const VALID_APPLICATION_LINK = "VALID_APPLICATION_LINK";
const VALID_APPLICATION_MONTH = "VALID_APPLICATION_MONTH";
const VALID_APPLICATION_SOURCE = "VALID_APPLICATION_SOURCE";
const VALID_APPLICATION_YEAR = "VALID_APPLICATION_YEAR";
// USERNAME FORM TYPES
const VALID_USERNAME = "VALID_USERNAME";
const VALID_EMAIL = "VALID_EMAIL";
const VALID_PASSWORD = "VALID_PASSWORD";
const VALID_IMAGE_URL = "VALID_IMAGE_URL";
// User Actions

export default {
  RETRIEVE_JOBS_LIST,
  RETRIEVE_JOBS_LIST_PAGINATION,
  RETRIEVE_SINGLE_JOB,
  RETRIEVE_DATA_ERROR,
  INCREASE_PAGINATION_BEGINNING,
  INCREASE_PAGINATION_ENDING,
  ADD_NEW_JOB,
  UPDATE_JOB_INFORMATION,
  DELETE_JOB,
  INITIALIZE_JOB_STATE,
  SUBMITTED_INPUT_COLLECTION,
  UPDATED_INPUT_FIELD,
  VALID_COMPANY_NAME,
  VALID_APPLICATION_LINK,
  VALID_APPLICATION_MONTH,
  VALID_APPLICATION_SOURCE,
  VALID_APPLICATION_YEAR,
  VALID_USERNAME,
  VALID_EMAIL,
  VALID_PASSWORD,
  VALID_IMAGE_URL
};
