// User Actions

// Job Actions
// GET REQUESTS
const RETRIEVE_JOBS_LIST = 'RETRIEVE_JOBS_LIST'
const RETRIEVE_JOBS_LIST_PAGINATION = 'RETRIEVE_JOBS_LIST_PAGINATION'
const RETRIEVE_SINGLE_JOB = 'RETRIEVE_SINGLE_JOB'
const RETRIEVE_DATA_ERROR = 'RETRIEVE_DATA_ERROR'
const INCREASE_PAGINATION_BEGINNING = 'INCREASE_PAGINATION_BEGINNING'
const INCREASE_PAGINATION_ENDING = 'INCREASE_PAGINATION_ENDING'
// POST REQUESTS
const ADD_NEW_JOB= 'ADD_NEW_JOB'
// PUT REQUESTS
const UPDATE_JOB_INFORMATION= 'UPDATE_JOB_INFORMATION'
// DELETE REQUESTS
const DELETE_JOB = 'DELETE_JOB'
const INITIALIZE_JOB_STATE = 'INITIALIZE_JOB_STATE'
const SUBMITTED_INPUT_COLLECTION = 'SUBMITTED_INPUT_COLLECTION'
const UPDATED_INPUT_FIELD = 'UPDATED_INPUT_FIELD'

export default {
    RETRIEVE_JOBS_LIST,
    RETRIEVE_JOBS_LIST_PAGINATION,
    RETRIEVE_SINGLE_JOB,
    RETRIEVE_DATA_ERROR,
    INCREASE_PAGINATION_BEGINNING,
    INCREASE_PAGINATION_ENDING,
    ADD_NEW_JOB,
    UPDATE_JOB_INFORMATION,
    DELETE_JOB,
    INITIALIZE_JOB_STATE,
    SUBMITTED_INPUT_COLLECTION,
    UPDATED_INPUT_FIELD
}