// Job Actions
const INITIALIZE_JOB_STATE = "INITIALIZE_JOB_STATE";
// GET REQUESTS
const RETRIEVE_JOBS_LIST = "RETRIEVE_JOBS_LIST";
const RETRIEVE_JOBS_LIST_PAGINATION = "RETRIEVE_JOBS_LIST_PAGINATION";
const RETRIEVE_SINGLE_JOB = "RETRIEVE_SINGLE_JOB";
const RETRIEVE_DATA_ERROR_JOBS = "RETRIEVE_DATA_ERROR_JOBS";
const INCREASE_JOBS_PAGINATION_BEGINNING = "INCREASE_JOBS_PAGINATION_BEGINNING";
const INCREASE_JOBS_PAGINATION_ENDING = "INCREASE_JOBS_PAGINATION_ENDING";
// POST REQUESTS
const ADD_NEW_JOB = "ADD_NEW_JOB";
const ADD_NEW_JOB_ERROR = "ADD_NEW_JOB_ERROR";
// PUT REQUESTS
const UPDATE_JOB_INFORMATION = "UPDATE_JOB_INFORMATION";
// DELETE REQUESTS
const DELETE_JOB = "DELETE_JOB";
//BULK UPLOAD
const CSV_JOBS_UPLOAD_VALID = "CSV_JOBS_UPLOAD_VALID";
const CSV_JOBS_UPLOAD_DATA = "CSV_JOBS_UPLOAD_DATA";
const CSV_JOBS_UPLOAD_CLEAR_DATA = "CSV_JOBS_UPLOAD_CLEAR_DATA";
const CSV_JOBS_UPLOAD_SUCCESSFULL = "CSV_JOBS_UPLOAD_SUCCESSFULL";

// Recruiter Actions
const INITIALIZE_RECRUITER_STATE = "INITIALIZE_JOB_STATE";
// GET REQUESTS
const RETRIEVE_RECRUITER_LIST = "RETRIEVE_RECRUITER_LIST";
const RETRIEVE_RECRUITER_LIST_PAGINATION = "RETRIEVE_RECRUITER_LIST_PAGINATION";
const RETRIEVE_SINGLE_RECRUITER = "RETRIEVE_SINGLE_RECRUITER";
const RETRIEVE_DATA_ERROR_RECRUITER = "RETRIEVE_DATA_ERROR_RECRUITER";
const INCREASE_PAGINATION_BEGINNING = "INCREASE_PAGINATION_BEGINNING";
const INCREASE_PAGINATION_ENDING = "INCREASE_PAGINATION_ENDING";
// POST REQUESTS
const ADD_NEW_RECRUITER = "ADD_NEW_RECRUITER";
const ADD_NEW_RECRUITER_ERROR = "ADD_NEW_RECRUITER_ERROR";
// PUT REQUESTS
const UPDATE_RECRUITER_INFORMATION = "UPDATE_RECRUITER_INFORMATION";
// DELETE REQUESTS
const DELETE_RECRUITER = "DELETE_RECRUITER";
//BULK UPLOAD
const CSV_RECRUITER_UPLOAD_VALID = "CSV_RECRUITER_UPLOAD_VALID";
const CSV_RECRUITER_UPLOAD_DATA = "CSV_RECRUITER_UPLOAD_DATA";
const CSV_RECRUITER_UPLOAD_CLEAR_DATA = "CSV_RECRUITER_UPLOAD_CLEAR_DATA";
const CSV_RECRUITER_UPLOAD_SUCCESSFULL = "CSV_RECRUITER_UPLOAD_SUCCESSFULL";

// UI Actions
// APPLICATION FORM TYPES
const VALID_COMPANY_NAME = "VALID_COMPANY_NAME";
const VALID_APPLICATION_LINK = "VALID_APPLICATION_LINK";
const VALID_APPLICATION_MONTH = "VALID_APPLICATION_MONTH";
const VALID_APPLICATION_SOURCE = "VALID_APPLICATION_SOURCE";
const VALID_APPLICATION_YEAR = "VALID_APPLICATION_YEAR";
// USERNAME FORM TYPES
const VALID_USERNAME = "VALID_USERNAME";
const VALID_EMAIL = "VALID_EMAIL";
const VALID_PASSWORD = "VALID_PASSWORD";
const VALID_IMAGE_URL = "VALID_IMAGE_URL";
// User Actions
const USER_CREATE = "USER_CREATE";
const USER_CREATE_SUCCESSFUL = "USER_CREATE_SUCCESSFUL";
const USER_CREATE_UNSUCCESSFUL = "USER_CREATE_UNSUCCESSFUL";
const USER_LOGIN = "USER_LOGIN";
const USER_LOGIN_SUCCESSFULL = "USER_LOGIN_SUCCESSFULL";
const USER_LOGIN_UNSUCCESSFUL = "USER_LOGIN_UNSUCCESSFUL";

//Form Actions
const UPDATED_RECRUITER_INPUT_FIELD = "UPDATED_RECRUITER_INPUT_FIELD";
const UPDATED_JOB_INPUT_FIELD = "UPDATED_JOB_INPUT_FIELD";

export default {
  RETRIEVE_JOBS_LIST,
  RETRIEVE_JOBS_LIST_PAGINATION,
  RETRIEVE_SINGLE_JOB,
  RETRIEVE_DATA_ERROR_JOBS,
  INCREASE_JOBS_PAGINATION_BEGINNING,
  INCREASE_JOBS_PAGINATION_ENDING,
  ADD_NEW_JOB,
  ADD_NEW_JOB_ERROR,
  UPDATE_JOB_INFORMATION,
  DELETE_JOB,
  INITIALIZE_JOB_STATE,
  CSV_JOBS_UPLOAD_VALID,
  CSV_JOBS_UPLOAD_DATA,
  CSV_JOBS_UPLOAD_CLEAR_DATA,
  CSV_JOBS_UPLOAD_SUCCESSFULL,
  INITIALIZE_RECRUITER_STATE,
  RETRIEVE_RECRUITER_LIST,
  RETRIEVE_RECRUITER_LIST_PAGINATION,
  RETRIEVE_SINGLE_RECRUITER,
  RETRIEVE_DATA_ERROR_RECRUITER,
  INCREASE_PAGINATION_BEGINNING,
  INCREASE_PAGINATION_ENDING,
  ADD_NEW_RECRUITER,
  ADD_NEW_RECRUITER_ERROR,
  UPDATE_RECRUITER_INFORMATION,
  DELETE_RECRUITER,
  CSV_RECRUITER_UPLOAD_VALID,
  CSV_RECRUITER_UPLOAD_DATA,
  CSV_RECRUITER_UPLOAD_CLEAR_DATA,
  CSV_RECRUITER_UPLOAD_SUCCESSFULL,
  VALID_COMPANY_NAME,
  VALID_APPLICATION_LINK,
  VALID_APPLICATION_MONTH,
  VALID_APPLICATION_SOURCE,
  VALID_APPLICATION_YEAR,
  VALID_USERNAME,
  VALID_EMAIL,
  VALID_PASSWORD,
  VALID_IMAGE_URL,
  USER_CREATE,
  USER_CREATE_SUCCESSFUL,
  USER_CREATE_UNSUCCESSFUL,
  USER_LOGIN,
  USER_LOGIN_SUCCESSFULL,
  USER_LOGIN_UNSUCCESSFUL,
  UPDATED_JOB_INPUT_FIELD,
  UPDATED_RECRUITER_INPUT_FIELD
};
